baseURL = 'https://info.ameliamnesia.xyz/'
languageCode = 'en-us'
title = 'ameliamnesia'
theme = 'hugo-tikva'


[params.navbar]
    style = "header" 
    colorScheme = "navbar-light"
    bgScheme = "bg-primary" # see Bootstrap docs, bg.* utilities https://getbootstrap.com/docs/4.1/utilities/colors/
    
    backgroundColor = ''

[params.theme]

    bootstrapTheme = 'darkly'
    backgroundColor = '' # If color is set, it will be used for background. Set empty for default.


[params.theme.header]
image = 'img/header_bg.jpg' # Use header image. This option is only valid if the theme is configured to the "header" style.

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1