baseURL = 'https://info.ameliamnesia.xyz/'
languageCode = 'en-us'
title = 'ameliamnesia'
theme = 'hugo-tikva'


[params.navbar]
    style = "header" 
    colorScheme = "navbar-dark"
    bgScheme = "bg-primary" # see Bootstrap docs, bg.* utilities https://getbootstrap.com/docs/4.1/utilities/colors/
    
    backgroundColor = ''

[params.theme]

    bootstrapTheme = 'cyborg'
    backgroundColor = '' # If color is set, it will be used for background. Set empty for default.


[params.theme.header]
    # The following options are mostly used when the navbar is in "header" mode, i.e. not fixed-top
    fontColor = '' # header font color, leave empty for default
    linkColor = '' # header link color, leave empty for default
    backgroundColor = '' # header background color, leave empty for default
image = 'img/header_bg.jpg' # Use header image. This option is only valid if the theme is configured to the "header" style.

[params.sidebar]
    enabled = true # default false; set to true to enable sidebar
    style = 'right' # options: 'left', 'right'. Left means sidebar on the left side, right displays the sidebar on the right side

    [[params.sidebar.demoColumn]]
    title = 'Example Content'

[params.fonts]
    navbarVariant = '800' # See above

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1