baseURL = 'https://info.ameliamnesia.xyz/'
languageCode = 'en-us'
title = 'ameliamnesia'
theme = 'hugo-arcana'

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1